<?php
/**
 * Created by PhpStorm.
 * User: adrian.ispas
 * Date: 8/1/2016
 * Time: 10:06 AM
 */

namespace AppBundle\Test;

use Doctrine\Common\DataFixtures\Purger\ORMPurger;
use GuzzleHttp\Client;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class ApiTestCase extends KernelTestCase
{

    public static $staticClient;

    /**
     * @var Client
     */
    protected $client;


    public static function setUpBeforeClass()
    {
        self::$staticClient = new Client([
            'base_url' => 'http://localhost:8000',
            'defaults' => [
                'exceptions' => false
            ]
        ]);

        self::bootKernel();
    }

    public function setup()
    {
        $this->client = self::$staticClient;
        $this->purgeDatabase();
    }

    public function tearDown()
    {
        // TODO: Change the autogenerated stub
    }

    private function purgeDatabase()
    {
        $purger = new ORMPurger($this->getService('doctrine')->getManager());
        $purger->purge();
    }

    protected function getService($id)
    {
        return self::$kernel->getContainer()->get($id);
    }

}